/*
 * Songvoter
 *
 * Definition for songvoter API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@coflnet.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.Authorization;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using .Attributes;
using .Models;

namespace .Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AuthApiController : ControllerBase
    { 
        /// <summary>
        /// Authenticate with google
        /// </summary>
        /// <remarks>Exchange a google identity token for a songvoter token</remarks>
        /// <param name="body">The google identity token</param>
        /// <response code="200">successful operation</response>
        [HttpPost]
        [Route("/v1/auth/google")]
        [ValidateModelState]
        [SwaggerOperation("AuthWithGoogle")]
        [SwaggerResponse(statusCode: 200, type: typeof(AuthToken), description: "successful operation")]
        public virtual IActionResult AuthWithGoogle([FromBody]AuthToken body)
        { 

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuthToken));
            string exampleJson = null;
            exampleJson = "{\n  \"token\" : \"ey...\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<AuthToken>(exampleJson)
            : default(AuthToken);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
