/*
 * Songvoter
 *
 * Definition for songvoter API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@coflnet.com
 * Generated by: https://openapi-generator.tech
 */
namespace Coflnet.SongVoter.Models;
using System;
using Coflnet.SongVoter.DBModels;
using Coflnet.SongVoter.Service;

public class Invite
{
    public string Link { get; set; }
    public DateTime Expiration { get; set; }

    public Invite(SongVoter.DBModels.Invite invite, IDService idService)
    {
        Link = $"https://songvoter.party/invite/{idService.ToHash(invite.Id)}";
        Expiration = invite.ValidUntil;
    }
}
