/*
 * Songvoter
 *
 * Definition for songvoter API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@coflnet.com
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Coflnet.SongVoter.Converters;

namespace Coflnet.SongVoter.Models
{
    /// <summary>
    /// The platform of this song
    /// </summary>
    /// <value>The platform of this song</value>
    [TypeConverter(typeof(CustomEnumConverter<SongPlatform>))]
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SongPlatform
    {

        /// <summary>
        /// Enum YoutubeEnum for youtube
        /// </summary>
        [EnumMember(Value = "youtube")]
        Youtube = 1,

        /// <summary>
        /// Enum SpotifyEnum for spotify
        /// </summary>
        [EnumMember(Value = "spotify")]
        Spotify = 2
    }
}
